[package]
name = "msptest"
version = "0.5.0"
edition = "2021"
authors = ["Jonathan Hudson <jh+github@daria.co.uk>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
getopts = "0.2"
crossbeam = "0.8.2"
crossbeam-channel = "0.5"
ctrlc = "3.2.4"
crossterm = "0.25.0"
iota = "0.2.2"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"