[package]
name = "msptest"
version = "0.1.0"
edition = "2018"
authors = ["Jonathan Hudson <jh+github@daria.co.uk>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
getopts = "0.2"
